var res = {
		mainNodeBg : "res/mainNodeBg.png",
		main_menuBg : "res/fire/menuBg.jpg",
		fire_logo : "res/fire/logo.png",
		main_btn_huo : "res/fire/buttons/huoyan.png",
		main_btn_huo_sel : "res/fire/buttons/huoyan_sel.png",
		main_btn_shu : "res/fire/buttons/shudu.png",
		main_btn_shu_sel : "res/fire/buttons/shudu_sel.png",
		main_btn_qita : "res/fire/buttons/qita.png",
		main_btn_qita_sel : "res/fire/buttons/qita_sel.png",
		fire_bg : "res/fire/bg.png",
		fire_back : "res/fire/buttons/back.png",
		fire_back_sel : "res/fire/buttons/back_sel.png",
		fire_guize : "res/fire/buttons/guize.png",
		fire_guize_sel : "res/fire/buttons/guize_sel.png",
		fire_back2list : "res/fire/buttons/back2list.png",
		fire_back2list_sel : "res/fire/buttons/back2list_sel.png",
		fire_cancel : "res/fire/buttons/cancel.png",
		fire_cancel_sel : "res/fire/buttons/cancel_sel.png",
		fire_chonglai : "res/fire/buttons/chonglai.png",
		fire_chonglai_sel : "res/fire/buttons/chonglai_sel.png",
		fire_huiqi : "res/fire/buttons/huiqi.png",
		fire_huiqi_sel : "res/fire/buttons/huiqi_sel.png",
		fire_ok : "res/fire/buttons/ok.png",
		fire_ok_sel : "res/fire/buttons/ok_sel.png",
		fire_pifu : "res/fire/buttons/pifu.png",
		fire_pifu_sel : "res/fire/buttons/pifu_sel.png",
		fire_jiaohuan : "res/fire/buttons/jiaohuan.png",
		fire_jiaohuan_sel : "res/fire/buttons/jiaohuan_sel.png",
		fire_close : "res/fire/buttons/close.png",
		fire_rr : "res/fire/buttons/rr.png",
		fire_rr_sel : "res/fire/buttons/rr_sel.png",
		fire_rj : "res/fire/buttons/rj.png",
		fire_rj_sel : "res/fire/buttons/rj_sel.png",
		fire_b2che : "res/fire/buttons/b2che.png",
		fire_b2ma : "res/fire/buttons/b2ma.png",
		fire_b2xiang : "res/fire/buttons/b2xiang.png",
		fire_b2hou : "res/fire/buttons/b2hou.png",
		fire_score_board : "res/fire/score_board.png",
		fire_playerA : "res/fire/playerA.png",
		fire_playerAI : "res/fire/playerAI.png",
		fire_dices_png : "res/fire/dices.png",
		fire_dices_plist : "res/fire/dices.plist",
		fire_dices_btn : "res/fire/dice.png",
		fire_time_plist : "res/fire/time.plist",
		fire_time_png : "res/fire/time.png",
		fire_qipan1 : "res/fire/skin1/qipan.png",
		fire_qipan2 : "res/fire/skin2/qipan.png",
		fire_qipan3 : "res/fire/skin3/qipan.png",
		fire_chess1_plist : "res/fire/skin1/chess.plist",
		fire_chess1_png : "res/fire/skin1/chess.png",
		fire_chess2_plist : "res/fire/skin2/chess.plist",
		fire_chess2_png : "res/fire/skin2/chess.png",
		fire_chess3_plist : "res/fire/skin3/chess.plist",
		fire_chess3_png : "res/fire/skin3/chess.png",
		fire_alertx : "res/fire/alertx.png",
		fire_alertb : "res/fire/alertb.png",
		fire_gameover : "res/fire/result.png",
    
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}