var res = {
		mainNodeBg : "res/mainNodeBg.png",
		main_menuBg : "res/menuBg.jpg",
		fire_menuBg : "res/fire/menuBg.jpg",
		fire_logo : "res/fire/logo.png",
		main_btn_huo : "res/fire/buttons/huoyan.png",
		main_btn_huo_sel : "res/fire/buttons/huoyan_sel.png",
		main_btn_shu : "res/fire/buttons/shudu.png",
		main_btn_shu_sel : "res/fire/buttons/shudu_sel.png",
		main_btn_shuSTD : "res/fire/buttons/shuduSTD.png",
		main_btn_shuSTD_sel : "res/fire/buttons/shuduSTD_sel.png",
		main_btn_qita : "res/fire/buttons/qita.png",
		main_btn_qita_sel : "res/fire/buttons/qita_sel.png",
		main_child_locked : "res/child_locked.png",
		main_child_opened : "res/child_opened.png",
		main_child_input : "res/child_input.png",
		
		fire_bg : "res/fire/bg.png",
		fire_back : "res/fire/buttons/back.png",
		fire_back_sel : "res/fire/buttons/back_sel.png",
		fire_guize : "res/fire/buttons/guize.png",
		fire_guize_sel : "res/fire/buttons/guize_sel.png",
		fire_back2list : "res/fire/buttons/back2list.png",
		fire_back2list_sel : "res/fire/buttons/back2list_sel.png",
		fire_chonglai : "res/fire/buttons/chonglai.png",
		fire_chonglai_sel : "res/fire/buttons/chonglai_sel.png",
		fire_huiqi : "res/fire/buttons/huiqi.png",
		fire_huiqi_sel : "res/fire/buttons/huiqi_sel.png",
		fire_ok : "res/fire/buttons/ok.png",
		fire_ok_sel : "res/fire/buttons/ok_sel.png",
		fire_cancel : "res/fire/buttons/cancel.png",
		fire_cancel_sel : "res/fire/buttons/cancel_sel.png",
		fire_pifu : "res/fire/buttons/pifu.png",
		fire_pifu_sel : "res/fire/buttons/pifu_sel.png",
		fire_jiaohuan : "res/fire/buttons/jiaohuan.png",
		fire_jiaohuan_sel : "res/fire/buttons/jiaohuan_sel.png",
		fire_close : "res/fire/buttons/close.png",
		fire_rr : "res/fire/buttons/rr.png",
		fire_rr_sel : "res/fire/buttons/rr_sel.png",
		fire_rj : "res/fire/buttons/rj.png",
		fire_rj_sel : "res/fire/buttons/rj_sel.png",
		fire_b2che : "res/fire/buttons/b2che.png",
		fire_b2ma : "res/fire/buttons/b2ma.png",
		fire_b2xiang : "res/fire/buttons/b2xiang.png",
		fire_b2hou : "res/fire/buttons/b2hou.png",
		fire_score_board : "res/fire/score_board.png",
		fire_playerA : "res/fire/playerA.png",
		fire_playerB : "res/fire/playerB.png",
		fire_playerAI : "res/fire/playerAI.png",
		fire_show_p_left : "res/fire/show_p_left.png",
		fire_show_p_right : "res/fire/show_p_right.png",
		fire_dices_png : "res/fire/dices.png",
		fire_dices_plist : "res/fire/dices.plist",
		fire_dices_btn : "res/fire/dice.png",
		fire_time_plist : "res/fire/time.plist",
		fire_time_png : "res/fire/time.png",
		fire_qipan1 : "res/fire/skin1/qipan.png",
		fire_qipan2 : "res/fire/skin2/qipan.png",
		fire_qipan3 : "res/fire/skin3/qipan.png",
		fire_chess1_plist : "res/fire/skin1/chess.plist",
		fire_chess1_png : "res/fire/skin1/chess.png",
		fire_chess2_plist : "res/fire/skin2/chess.plist",
		fire_chess2_png : "res/fire/skin2/chess.png",
		fire_chess3_plist : "res/fire/skin3/chess.plist",
		fire_chess3_png : "res/fire/skin3/chess.png",
		fire_alertx : "res/fire/alertx.png",
		fire_alertb : "res/fire/alertb.png",
		fire_alertBG_body : "res/fire/alertBG_body.png",
		fire_alertBG_top : "res/fire/alertBG_top.png",
		fire_gameover : "res/fire/result.png",
		fire_rule_plist : "res/fire/rule/fire_rule.plist",
		fire_rule_png : "res/fire/rule/fire_rule.png",
		fire_rule_go1 : "res/fire/rule/go1.png",
		fire_rule_go2 : "res/fire/rule/go2.png",
		fire_rule_go3 : "res/fire/rule/go3.png",
		fire_rule_go4 : "res/fire/rule/go4.png",
		fire_rule_go5 : "res/fire/rule/go5.png",
		fire_rule_go6 : "res/fire/rule/go6.png",
		fire_rule_put1 : "res/fire/rule/put1.png",
		fire_rule_put2 : "res/fire/rule/put2.png",
		fire_rule_put3 : "res/fire/rule/put3.png",
		fire_rule_put4 : "res/fire/rule/put4.png",
		
		
		//音频
		fire_au_beep : "res/fire/au/beep.mp3",	//按钮
		fire_au_click : "res/fire/au/click.mp3",	//选中棋子
		fire_au_click1 : "res/fire/au/click1.mp3",
		fire_au_connect : "res/fire/au/connect.mp3",	//胜利
		fire_au_dconnect : "res/fire/au/dconnect.mp3",	//失败 ，平
		fire_au_dead1 : "res/fire/au/dead1.mp3",
		fire_au_dice : "res/fire/au/dice.mp3",	//骰子
		fire_au_error1 : "res/fire/au/error1.mp3",	//错误
		fire_au_move : "res/fire/au/move.mp3",	//走棋
		fire_au_moveerr : "res/fire/au/moveerr.mp3",
		
		
		//数独
		sd_ok : "res/fire/buttons/ok.png",
		sd_ok_sel : "res/fire/buttons/ok_sel.png",
		sd_cancel : "res/fire/buttons/cancel.png",
		sd_cancel_sel : "res/fire/buttons/cancel_sel.png",
		sd_HelloWorld_png : "res/shudu/HelloWorld.jpg",
		sd_qt_sel : 		"res/shudu/qt_sel.png",
		sd_qt_dissel : 		"res/shudu/qt_dissel.png",
		sd_start_png : 		"res/shudu/start.png",
		sd_start_sel_png : 		"res/shudu/starts.png",
		sd_btn1 : 			"res/shudu/btn1.png",
		sd_btn1s : 			"res/shudu/btn1s.png",
		sd_btn2 : 			"res/shudu/btn2.png",
		sd_btn2s : 			"res/shudu/btn2s.png",
		sd_btn3 : 			"res/shudu/btn3.png",
		sd_btn3s : 			"res/shudu/btn3s.png",
		sd_btn3d : 			"res/shudu/btn3d.png",
		sd_subBtn : 		"res/shudu/subBtn.png",
		sd_back_png : 		"res/shudu/back.png",
		sd_back_sel_png : 		"res/shudu/back_sel.png",
		sd_right_png : 		"res/shudu/right.png",
		sd_right_sel_png : 		"res/shudu/right_sel.png",
		sd_time_panel : 	"res/shudu/time_panel.png",
		sd_msgNum : 		"res/shudu/msg_num.png",
		sd_next : 		"res/shudu/next.png",
		sd_nexts : 		"res/shudu/nexts.png",
		sd_replay : 		"res/shudu/replay.png",
		sd_replay2 : 		"res/shudu/replay2.png",
		sd_replay2s : 		"res/shudu/replay2s.png",
		sd_continue : 		"res/shudu/continue.png",
		sd_continues : 		"res/shudu/continues.png",
		sd_btnOpen : 		"res/shudu/open.png",
		sd_btnOpen_sel : 		"res/shudu/opens.png",
		sd_btnOpen_dis : 		"res/shudu/opend.png",
		sd_jiesuan : 		"res/shudu/jiesuan.png",
		sd_jiesuan2 : 		"res/shudu/jiesuan2.png",	//标准数独
		sd_topList : 		"res/shudu/top-list.png",
		sd_topLists : 		"res/shudu/top-lists.png",
		sd_scan : 		"res/shudu/scan.png",
		sd_scans : 		"res/shudu/scan_sel.png",
		sd_sel1 : 			"res/shudu/sel1.png",
		sd_sel1s : 			"res/shudu/sel1s.png",
		sd_sel2 : 			"res/shudu/sel2.png",
		sd_sel2s : 			"res/shudu/sel2s.png",
		sd_sel3 : 			"res/shudu/sel3.png",
		sd_sel3s : 			"res/shudu/sel3s.png",
		sd_sel3d : 			"res/shudu/sel3d.png",
		sd_selBtnPenal : 			"res/shudu/selBtnPenal.png",
		sd_topListBg : 			"res/shudu/top_list.png",
                                 
		sd_q3 : 			"res/shudu/q3.png",
		sd_q3_1_1 : 		"res/shudu/q3_1_1.png",
		sd_q3_1_2 : 		"res/shudu/q3_1_2.png",
		sd_q3_1_3 : 		"res/shudu/q3_1_3.png",
		sd_q3_1_4 : 		"res/shudu/q3_1_4.png",
		sd_q3_1_5 : 		"res/shudu/q3_1_5.png",
		sd_q3_1_6 : 		"res/shudu/q3_1_6.png",
		sd_btn_1_1 : 		"res/shudu/btn_1_1.png",
		sd_btn_1_2 : 		"res/shudu/btn_1_2.png",
		sd_btn_1_3 : 		"res/shudu/btn_1_3.png",
		sd_btn_1_4 : 		"res/shudu/btn_1_4.png",
		sd_btn_1_5 : 		"res/shudu/btn_1_5.png",
		sd_btn_1_6 : 		"res/shudu/btn_1_6.png",
		sd_btn_1_1s : 		"res/shudu/btn_1_1s.png",
		sd_btn_1_2s : 		"res/shudu/btn_1_2s.png",
		sd_btn_1_3s : 		"res/shudu/btn_1_3s.png",
		sd_btn_1_4s : 		"res/shudu/btn_1_4s.png",
		sd_btn_1_5s : 		"res/shudu/btn_1_5s.png",
		sd_btn_1_6s : 		"res/shudu/btn_1_6s.png",
		sd_q3_2_1 : 		"res/shudu/q3_2_1.png",
		sd_q3_2_2 : 		"res/shudu/q3_2_2.png",
		sd_q3_2_3 : 		"res/shudu/q3_2_3.png",
		sd_q3_2_4 : 		"res/shudu/q3_2_4.png",
		sd_q3_2_5 : 		"res/shudu/q3_2_5.png",
		sd_q3_2_6 : 		"res/shudu/q3_2_6.png",
		sd_btn_2_1 : 		"res/shudu/btn_2_1.png",
		sd_btn_2_2 : 		"res/shudu/btn_2_2.png",
		sd_btn_2_3 : 		"res/shudu/btn_2_3.png",
		sd_btn_2_4 : 		"res/shudu/btn_2_4.png",
		sd_btn_2_5 : 		"res/shudu/btn_2_5.png",
		sd_btn_2_6 : 		"res/shudu/btn_2_6.png",
		sd_btn_2_1s : 		"res/shudu/btn_2_1s.png",
		sd_btn_2_2s : 		"res/shudu/btn_2_2s.png",
		sd_btn_2_3s : 		"res/shudu/btn_2_3s.png",
		sd_btn_2_4s : 		"res/shudu/btn_2_4s.png",
		sd_btn_2_5s : 		"res/shudu/btn_2_5s.png",
		sd_btn_2_6s : 		"res/shudu/btn_2_6s.png",
		sd_btn_3_1 : 		"res/shudu/btn_3_1.png",
		sd_btn_3_2 : 		"res/shudu/btn_3_2.png",
		sd_btn_3_3 : 		"res/shudu/btn_3_3.png",
		sd_btn_3_4 : 		"res/shudu/btn_3_4.png",
		sd_btn_3_5 : 		"res/shudu/btn_3_5.png",
		sd_btn_3_6 : 		"res/shudu/btn_3_6.png",
		sd_btn_3_1s : 		"res/shudu/btn_3_1s.png",
		sd_btn_3_2s : 		"res/shudu/btn_3_2s.png",
		sd_btn_3_3s : 		"res/shudu/btn_3_3s.png",
		sd_btn_3_4s : 		"res/shudu/btn_3_4s.png",
		sd_btn_3_5s : 		"res/shudu/btn_3_5s.png",
		sd_btn_3_6s : 		"res/shudu/btn_3_6s.png",
		
		sd_q3_3_1 : 		"res/shudu/q3_3_1.png",
		sd_q3_3_2 : 		"res/shudu/q3_3_2.png",
		sd_q3_3_3 : 		"res/shudu/q3_3_3.png",
		sd_q3_3_4 : 		"res/shudu/q3_3_4.png",
		sd_q3_3_5 : 		"res/shudu/q3_3_5.png",
		sd_q3_3_6 : 		"res/shudu/q3_3_6.png",
        
		sd_q4 : "res/shudu/q4.png",
		sd_q6 : "res/shudu/q6.png",
		sd_btn_answer : "res/shudu/btn_answer.png",
		sd_btn_answers : "res/shudu/btn_answers.png",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}